// SmartSuite Field ID Mappings
// These are auto-generated by SmartSuite and differ from display names

export const USER_FIELDS = {
  clerk_id: 's380097484',
  email: 'sf07816b54',
  full_name: 'sd73b239d6',
  company_name: 'sd3553da44',
  niceic_number: 's9a8533fc1',
  phone: 's6b9c05836',
  subscription_status: 's6ce94d029',
  stripe_customer_id: 'sd3719d8cc',
  last_login: 'sa124ad39b'
} as const

// We'll add Jobs, Tasks, Evidence, Audit Packs fields next
export const JOB_FIELDS = {} as const
export const TASK_FIELDS = {} as const
export const EVIDENCE_FIELDS = {} as const
export const AUDIT_PACK_FIELDS = {} as const
