// SmartSuite Field ID Mappings
// These are auto-generated by SmartSuite and differ from display names
export const USER_FIELDS = {
  clerk_id: 's380097484',
  email: 'sf07816b54',
  full_name: 'sd73b239d6',
  company_name: 'sd3553da44',
  niceic_number: 's9a8533fc1',
  phone: 's6b9c05836',
  subscription_status: 's6ce94d029',
  stripe_customer_id: 'sd3719d8cc',
  last_login: 'sa124ad39b'
} as const
export const JOB_FIELDS = {
  user: 's11e8c3905',
  title: 's81dd1e60e',
  address: 's12140605b',
  postcode: 's3529ab4e0',
  client_name: 's265bc1e01',
  client_phone: 'sffc9c0134',
  client_email: 's7c5f10ae9',
  status: 's71ac612d3',
  start_date: 'sa5e86ccaf',
  completion_date: 'se01dd301e',
  notes: 's0b41ef34e',
  created_at: 'sccc9692c5'
} as const
export const TASK_FIELDS = {
  job: 'sdae9777c2',
  task_type: 's49488096d',
  status: 's4fd7b0b93',
  order: 's39c59659e',
  notes: 's351243277',
  started_at: 'sf16099920',
  completed_at: 's1f73c92ac'
} as const
export const EVIDENCE_FIELDS = {
  task: 's9d23ccc51',
  job: 's662723b29',
  evidence_type: 'sc1907f924',
  photo_stage: 's15d91de07',
  photo_url: 'sed7082c34',
  photo_hash: 's8ef18ff24',
  latitude: 'sc08cda9ac',
  longitude: 'sc056ca7e2',
  gps_accuracy: 'sb938a3c3a',
  captured_at: 's7f7ca3c0b',
  synced_at: 'sbb369206b',
  is_synced: 'scfeb49a6e',
  notes: 's17b3f606b'
} as const
export const AUDIT_PACK_FIELDS = {
  job: 'sc9f8fa1a7',
  generated_at: 's6ba4184ab',
  pdf_url: 's5eeb945bb',
  evidence_count: 's8a866c291',
  hash: 'sbf0136ef8',
  downloaded_at: 'sdafb72e64',
  shared_with: 'sb0a19da8f',
  signature_url: 's5fe1c92f8',
  signed_at: 'sd121393c3'
} as const
// Evidence Type: App Key -> SmartSuite Option ID
// Used when saving evidence to convert app keys to SmartSuite IDs
export const EVIDENCE_TYPE_IDS: Record<string, string> = {
  // Consumer Unit
  existing_board_condition: 'mVsNo',
  isolation_confirmation: 'FTVO5',
  new_board_installed: 'RvRbr',
  main_earth_bonding: '3jYOf',
  completed_installation: 'Q5wfk',
  
  // Rewire
  cable_route: 'nLeez',
  containment: 'YFZBw',
  connection_points: 'cN18H',
  db_photo: '1YrTO',
  
  // EICR
  sample_circuit_tests: 'F826r',
  defects_found: 'E2lOv',
  
  // Emergency Lighting
  luminaire_photo: 'sMhQ9',
  battery_test_readings: '1M3gg',
  logbook_entry: 'nZKk1',
  
  // Fire Alarm
  panel_photo: 'XNwfW',
  device_test_log: 'jSpIt',
  call_point_activation: 'CxWPt',
  
  // EV Charger
  location_photo: 'gLnR1',
  protective_device: 'XMyuc',
  dno_notification: 'SfzfC',
  
  // Fault Finding
  initial_fault_indication: '3FyTK',
  investigation_photos: 'dvGWa',
  resolution: '8aZOR',
  test_confirmation: 'zHfbD',
  
  // PAT Testing
  equipment_photo: 'x0eqD',
  label_applied: 'c7LhE',
  test_result: 'yoJ7D',
  
  // Smoke Alarm
  location_compliance: 'hRjl8',
  alarm_photo: 'xaQrd',
  test_activation: 'xKIP1',
  
  // Solar PV
  array_location: 'fDfmf',
  inverter: 'YO3iv',
  ac_dc_isolators: '708g2',
  g98_g99_submission: 'OJe8U',
  dno_acceptance: 'KtV9n',
  
  // Bathroom
  zone_identification: '537Fm',
  rcd_protection: '5ZTN3',
  bonding_connections: 'ShjqB',
  
  // Kitchen
  circuit_layout: 'fCB6P',
  isolation_switch: 'SivU5',
  
  // Data/Network
  device_locations: 'XjFcs',
  
  // CCTV
  camera_locations: '42Gf9',
  recorder_location: 's4R4Q',
  
  // Common/Shared
  before_photo: '4hldz',
  after_photo: 'bPV1p',
  test_meter_readings: 'uR5fB',
  certificate_photo: '1VlrY',
  labelling: 'c7LhE',
  test_instrument_calibration: 'X3Lrf',
  earthing_arrangement: 'qytQX',
  wiring_photo: 'f2QeD',
  additional_evidence: 'Dxpai'
} as const
// Reverse mapping: SmartSuite Option ID -> App Key
// Used when reading evidence to convert SmartSuite IDs back to app keys
export const EVIDENCE_TYPE_KEYS: Record<string, string> = Object.fromEntries(
  Object.entries(EVIDENCE_TYPE_IDS).map(([key, value]) => [value, key])
)
